<h1>Bücher</h1>

<?php if(count($this->books) > 0):
	echo $this->datatable($this->books, 'book', array(
		'keys' => array(
			array(
				'name' => 'title',
				'headline' => 'Titel'
			),
			array(
				'name' => 'pages',
				'headline' => 'Seiten'
			),
			array(
				'name' => 'id_author',
				'headline' => 'Autor ID'
			),
			array(
				'name' => 'releaseDate',
				'type' => 'date',
				'headline' => 'Erscheinungsdatum'
			)
		),
		'actions' => array(
			array(
				'name' => 'show',
				'title' => 'Anzeigen'
			),			
			array(
				'name' => 'edit',
				'title' => 'Bearbeiten'
			),			
			array(
				'name' => 'delete',
				'title' => 'Löschen'
			),
		)
	));
else: 
?>
	<div class="alert alert-warning" role="alert">Keine Bücher vorhanden</div>
<?php 
endif; 
?>

<a class="btn btn-default" href="<?php echo $this->url('book', array('action' => 'add'));?>">Hinzufügen</a>