<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap-datetimepicker-de.js')
            ->prependFile($this->basePath() . '/js/bootstrap-datetimepicker.js')
            ->prependFile($this->basePath() . '/js/moment.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <script>
        	$(function() {
	        	$('.datetimepicker').datetimepicker({
		        	language: 'de',
		        	pickTime: false
	        	});
        	});
		</script>

    </head>
    <body>
       <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('ARMA-Projektwoche') ?></a>
                </div>
                <div class="collapse navbar-collapse">
			        <?php echo $this->navigation(($this->loggedIn) ? ($this->identity->role == 2) ? 'member_navigation' : 'app_navigation' : 'guest_navigation')
			        					->menu()
			        					->setMinDepth(0)
			        					->setMaxDepth(0)
			        					->setUlClass('nav navbar-nav')
			        					->render(); 
			        
			        if($this->loggedIn): ?>
			        
			        <ul class="nav navbar-nav navbar-right">
				        <li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Eingeloggt als <strong><?php echo $this->identity->username ?></strong> <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				            <li><a href="<?php echo $this->url('logout') ?>">Logout</a></li>
				          </ul>
				        </li>
			      </ul>
			      
			      <?php endif; ?>
			        
                </div><!--/.nav-collapse -->
            </div>
        </nav>
                
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
