<h1>Nutzer</h1>

<?php if(count($this->users) > 0):
	echo $this->datatable($this->users, 'user', array(
		'keys' => array(
			array(
				'name' => 'username',
				'headline' => 'Username'
			),
			array(
				'name' => 'password',
				'headline' => 'Passwort'
			),
			array(
				'name' => 'role',
				'headline' => 'Rolle'
			)
		),
		'actions' => array(
			array(
				'name' => 'show',
				'title' => 'Anzeigen'
			),			
			array(
				'name' => 'edit',
				'title' => 'Bearbeiten'
			),			
			array(
				'name' => 'delete',
				'title' => 'Löschen'
			),
		)
	));
else: 
?>

<div class="alert alert-warning" role="alert">Keine Nutzer vorhanden</div>

<?php  endif;  ?>

<a class="btn btn-default" href="<?php echo $this->url('user', array('action' => 'add'));?>">Hinzufügen</a>