<h1>Autoren</h1>

<?php if(count($this->authors) > 0):
	echo $this->datatable($this->authors, 'author', array(
		'keys' => array(
			array(
				'name' => 'first_name',
				'headline' => 'Vorname'
			),
			array(
				'name' => 'last_name',
				'headline' => 'Nachname'
			)
		),
		'actions' => array(
			array(
				'name' => 'show',
				'title' => 'Anzeigen'
			),			
			array(
				'name' => 'edit',
				'title' => 'Bearbeiten'
			),			
			array(
				'name' => 'delete',
				'title' => 'Löschen'
			),
		)
	));
else: 
?>

<div class="alert alert-warning" role="alert">Keine Autoren vorhanden</div>

<?php  endif;  ?>

<a class="btn btn-default" href="<?php echo $this->url('author', array('action' => 'add'));?>">Hinzufügen</a>